// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OWN.Repository.Tables
{
    [Table("Address", Schema = "SalesLT")]
    /// <summary>
    /// Street address information for customers.
    /// </summary>
    public partial class Address : BaseEntity<int>
    {
        [Key]
        [Column("AddressID")]
        [Required]
        [StringLength(60)]
        /// <summary>
        /// Primary key for Address records.
        /// </summary>
        public override int Id { get; set; }

        [Required]
        [StringLength(60)]
        /// <summary>
        /// First street address line.
        /// </summary>
        public string AddressLine1 { get; set; }
        [StringLength(60)]
        /// <summary>
        /// Second street address line.
        /// </summary>
        public string AddressLine2 { get; set; }
        [Required]
        [StringLength(30)]
        /// <summary>
        /// Name of the city.
        /// </summary>
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// Name of state or province.
        /// </summary>
        public string StateProvince { get; set; }
        [Required]
        [StringLength(50)]
        public string CountryRegion { get; set; }
        [Required]
        [StringLength(15)]
        /// <summary>
        /// Postal code for the street address.
        /// </summary>
        public string PostalCode { get; set; }
        [Column("rowguid")]
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public Guid Rowguid { get; set; }
        [Column(TypeName = "datetime")]
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; }
    }
}